// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package menu

import (
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/menu/internal/event"
	"github.com/userreksai/ecmdb-main/internal/menu/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/menu/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/menu/internal/service"
	"github.com/userreksai/ecmdb-main/internal/menu/internal/web"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, db *mongox.Mongo) (*Module, error) {
	menuDAO := dao.NewMenuDAO(db)
	menuRepository := repository.NewMenuRepository(menuDAO)
	menuChangeEventProducer, err := event.NewMenuChangeEventProducer(q)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(menuRepository, menuChangeEventProducer)
	v := web.NewHandler(serviceService)
	module := &Module{
		Hdl: v,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewMenuRepository, dao.NewMenuDAO)
