// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package policy

import (
	"github.com/casbin/casbin/v2"
	"github.com/ecodeclub/ginx/session"
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/pkg/servicetoken"
	"github.com/userreksai/ecmdb-main/internal/policy/internal/grpc"
	"github.com/userreksai/ecmdb-main/internal/policy/internal/service"
	"github.com/userreksai/ecmdb-main/internal/policy/internal/web"
)

// Injectors from wire.go:

func InitModule(enforcer *casbin.SyncedEnforcer, sp session.Provider, tokenMgr *servicetoken.Manager) (*Module, error) {
	serviceService := service.NewService(enforcer)
	v := web.NewHandler(serviceService, sp, tokenMgr)
	v2 := grpc.NewPolicyServer(serviceService, sp)
	module := &Module{
		Hdl:       v,
		Svc:       serviceService,
		RpcServer: v2,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, grpc.NewPolicyServer)
