// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dataio

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/attribute"
	"github.com/userreksai/ecmdb-main/internal/dataio/internal/service"
	"github.com/userreksai/ecmdb-main/internal/dataio/internal/web"
	"github.com/userreksai/ecmdb-main/internal/model"
	"github.com/userreksai/ecmdb-main/internal/operationlog"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/relation"
	"github.com/userreksai/ecmdb-main/internal/resource"
	"github.com/userreksai/ecmdb-main/internal/role"
	"github.com/userreksai/ecmdb-main/pkg/storage"
)

// Injectors from wire.go:

func InitModule(attributeModule *attribute.Module, resourceModule *resource.Module, storage2 *storage.S3Storage, modelModule *model.Module, relationModule *relation.Module, roleModule *role.Module, policyModule *policy.Module, operationLogModule *operationlog.Module) (*Module, error) {
	v := attributeModule.Svc
	v2 := resourceModule.EncryptedSvc
	v3 := modelModule.Svc
	v4 := relationModule.RMSvc
	v5 := relationModule.RRSvc
	iDataIOService := service.NewDataIOService(v, v2, v3, v4, v5)
	v6 := roleModule.Svc
	v7 := policyModule.Svc
	operationlogService := operationLogModule.Svc
	v8 := web.NewHandler(iDataIOService, storage2, v6, v7, operationlogService, v)
	module := &Module{
		Hdl: v8,
	}
	return module, nil
}

// wire.go:

// ProviderSet 数据交换模块依赖集合
var ProviderSet = wire.NewSet(web.NewHandler, service.NewDataIOService)
