// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workflow

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/engine"
	"github.com/userreksai/ecmdb-main/internal/workflow/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/workflow/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/workflow/internal/service"
	"github.com/userreksai/ecmdb-main/internal/workflow/internal/web"
	"github.com/userreksai/ecmdb-main/internal/workflow/pkg/easyflow"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, engineModule *engine.Module) (*Module, error) {
	workflowDAO := dao.NewWorkflowDAO(db)
	snapshotDAO := dao.NewSnapshotDAO(db)
	workflowRepository := repository.NewWorkflowRepository(workflowDAO, snapshotDAO)
	notifyBindingDAO := dao.NewNotifyBindingDAO(db)
	notifyBindingRepository := repository.NewNotifyBindingRepository(notifyBindingDAO)
	v := engineModule.Svc
	converter := easyflow.NewLogicFlowToEngineConvert()
	serviceService := service.NewService(workflowRepository, notifyBindingRepository, v, converter)
	handler := web.NewHandler(serviceService, v)
	module := &Module{
		Hdl: handler,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewWorkflowRepository, repository.NewNotifyBindingRepository, dao.NewWorkflowDAO, dao.NewSnapshotDAO, dao.NewNotifyBindingDAO, easyflow.NewLogicFlowToEngineConvert)
