// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package codebook

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/codebook/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/codebook/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/codebook/internal/service"
	"github.com/userreksai/ecmdb-main/internal/codebook/internal/web"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	codebookDAO := dao.NewCodebookDAO(db)
	codebookRepository := repository.NewCodebookRepository(codebookDAO)
	serviceService := service.NewService(codebookRepository)
	v := web.NewHandler(serviceService)
	module := &Module{
		Hdl: v,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewCodebookRepository, dao.NewCodebookDAO)
