// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runner

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/codebook"
	"github.com/userreksai/ecmdb-main/internal/runner/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/runner/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/runner/internal/service"
	"github.com/userreksai/ecmdb-main/internal/runner/internal/web"
	"github.com/userreksai/ecmdb-main/internal/workflow"
	"github.com/userreksai/ecmdb-main/pkg/cryptox"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, workflowSvc *workflow.Module, codebookModule *codebook.Module, crypto *cryptox.CryptoRegistry) (*Module, error) {
	runnerDAO := dao.NewRunnerDAO(db)
	runnerRepository := repository.NewRunnerRepository(runnerDAO)
	serviceService := service.NewService(runnerRepository)
	v := workflowSvc.Svc
	v2 := codebookModule.Svc
	cryptoxCrypto := InitCrypto(crypto)
	handler := web.NewHandler(serviceService, v, v2, cryptoxCrypto)
	module := &Module{
		Svc: serviceService,
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewRunnerRepository, dao.NewRunnerDAO)

func InitCrypto(reg *cryptox.CryptoRegistry) cryptox.Crypto {
	return reg.Runner
}
