// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/role/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/role/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/role/internal/service"
	"github.com/userreksai/ecmdb-main/internal/role/internal/web"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	roleDAO := InitRoleDAO(db)
	roleRepository := repository.NewRoleRepository(roleDAO)
	serviceService := service.NewService(roleRepository)
	v := web.NewHandler(serviceService)
	module := &Module{
		Hdl: v,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewRoleRepository)

var daoOnce = sync.Once{}

func InitCollectionOnce(db *mongox.Mongo) {
	daoOnce.Do(func() {
		err := dao.InitIndexes(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitRoleDAO(db *mongox.Mongo) dao.RoleDAO {
	InitCollectionOnce(db)
	return dao.NewRoleDAO(db)
}
