// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package event

import (
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/larksuite/oapi-sdk-go/v3"
	engine2 "github.com/userreksai/easy-workflow/workflow/engine"
	"github.com/userreksai/ecmdb-main/api/proto/gen/ealert/notification/v1"
	"github.com/userreksai/ecmdb-main/api/proto/gen/ealert/team"
	"github.com/userreksai/ecmdb-main/internal/department"
	"github.com/userreksai/ecmdb-main/internal/engine"
	"github.com/userreksai/ecmdb-main/internal/event/producer"
	"github.com/userreksai/ecmdb-main/internal/event/service/assignees"
	"github.com/userreksai/ecmdb-main/internal/event/service/easyflow"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/automation"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/carbon_copy"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/chat"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/start"
	user2 "github.com/userreksai/ecmdb-main/internal/event/service/strategy/user"
	"github.com/userreksai/ecmdb-main/internal/order"
	"github.com/userreksai/ecmdb-main/internal/pkg/notification/sender"
	"github.com/userreksai/ecmdb-main/internal/rota"
	"github.com/userreksai/ecmdb-main/internal/task"
	"github.com/userreksai/ecmdb-main/internal/template"
	"github.com/userreksai/ecmdb-main/internal/user"
	"github.com/userreksai/ecmdb-main/internal/workflow"
	"github.com/userreksai/ecmdb-main/pkg/resolve"
	"gorm.io/gorm"
	"log"
	"sync"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, db *gorm.DB, engineModule *engine.Module, taskModule *task.Module, orderModule *order.Module, templateModule *template.Module, userModule *user.Module, workflowModule *workflow.Module, sender2 sender.NotificationSender, departmentModule *department.Module, rotaModule *rota.Module, lark2 *lark.Client, notificationSvc notificationv1.NotificationServiceClient, teamSvc teamv1.TeamServiceClient) (*Module, error) {
	v := engineModule.Svc
	orderStatusModifyEventProducer, err := producer.NewOrderStatusModifyEventProducer(q)
	if err != nil {
		return nil, err
	}
	v2 := taskModule.Svc
	v3 := orderModule.Svc
	v4 := workflowModule.Svc
	v5 := userModule.Svc
	v6 := templateModule.Svc
	appointResolver := assignees.NewAppointResolver(v5)
	founderResolver := assignees.NewFounderResolver(v5)
	v7 := departmentModule.Svc
	leaderResolver := assignees.NewLeaderResolver(v5, v7)
	mainLeaderResolver := assignees.NewMainLeaderResolver(v5, v7)
	v8 := rotaModule.Svc
	onCallResolver := assignees.NewOnCallResolver(v8, v5)
	templateResolver := assignees.NewTemplateResolver(v5)
	teamResolver := assignees.NewTeamResolver(teamSvc, v5)
	resolveEngine := InitResolveEngine(appointResolver, founderResolver, leaderResolver, mainLeaderResolver, onCallResolver, templateResolver, teamResolver)
	service := strategy.NewService(v5, v6, v2, v3, v, resolveEngine)
	notification := user2.NewNotification(service, v7, sender2, notificationSvc)
	automationNotification := automation.NewNotification(service, sender2)
	startNotification := start.NewNotification(service, sender2)
	chatNotification := chat.NewNotification(service, sender2, lark2, teamSvc)
	carbon_copyNotification := carbon_copy.NewNotification(service, sender2)
	dispatcher := ProviderNewDispatcher(notification, automationNotification, startNotification, chatNotification, carbon_copyNotification, service)
	processEvent := InitWorkflowEngineOnce(db, v, orderStatusModifyEventProducer, v2, v3, v4, dispatcher)
	module := &Module{
		Event: processEvent,
	}
	return module, nil
}

// wire.go:

var InitStrategySet = wire.NewSet(strategy.NewService, user2.NewNotification, automation.NewNotification, start.NewNotification, chat.NewNotification, carbon_copy.NewNotification, ProviderNewDispatcher, wire.Bind(new(strategy.SendStrategy), new(*strategy.Dispatcher)), assignees.NewAppointResolver, assignees.NewFounderResolver, assignees.NewLeaderResolver, assignees.NewMainLeaderResolver, assignees.NewOnCallResolver, assignees.NewTemplateResolver, assignees.NewTeamResolver, InitResolveEngine)

func InitResolveEngine(
	appoint *assignees.AppointResolver,
	founder *assignees.FounderResolver,
	leader *assignees.LeaderResolver,
	mainLeader *assignees.MainLeaderResolver,
	onCall *assignees.OnCallResolver, template2 *assignees.TemplateResolver,
	team *assignees.TeamResolver,
) resolve.Engine {
	return resolve.NewEngine().Register(
		appoint,
		founder,
		leader,
		mainLeader,
		onCall, template2, team,
	)
}

var engineOnce = sync.Once{}

func InitWorkflowEngineOnce(db *gorm.DB, engineSvc engine.Service, producer2 producer.OrderStatusModifyEventProducer,
	taskSvc task.Service, orderSvc order.Service, workflowSvc workflow.Service, strategy2 strategy.SendStrategy,
) *easyflow.ProcessEvent {
	event, err := easyflow.NewProcessEvent(producer2, engineSvc, taskSvc, orderSvc, workflowSvc, strategy2)
	if err != nil {
		panic(err)
	}

	engineOnce.Do(func() {
		engine2.DB = db
		if err = engine2.DatabaseInitialize(); err != nil {
			log.Fatalln("easy workflow 初始化数据表失败，错误:", err)
		}
		engine2.IgnoreEventError = false
	})

	return event
}

func ProviderNewDispatcher(user3 *user2.Notification,
	auto *automation.Notification, start2 *start.Notification, chat2 *chat.Notification,
	cc *carbon_copy.Notification,
	base strategy.Service,
) *strategy.Dispatcher {
	return strategy.NewDispatcher(user3, auto, start2, chat2, cc, base)
}
