// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"github.com/userreksai/ecmdb-main/api/proto/gen/ealert/template/v1"
	"github.com/userreksai/ecmdb-main/cmd/initial/version"
	"github.com/userreksai/ecmdb-main/internal/attribute"
	"github.com/userreksai/ecmdb-main/internal/bootstrap"
	"github.com/userreksai/ecmdb-main/internal/department"
	"github.com/userreksai/ecmdb-main/internal/engine"
	"github.com/userreksai/ecmdb-main/internal/menu"
	"github.com/userreksai/ecmdb-main/internal/model"
	"github.com/userreksai/ecmdb-main/internal/operationlog"
	"github.com/userreksai/ecmdb-main/internal/permission"
	"github.com/userreksai/ecmdb-main/internal/pkg/servicetoken"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/relation"
	"github.com/userreksai/ecmdb-main/internal/resource"
	"github.com/userreksai/ecmdb-main/internal/role"
	"github.com/userreksai/ecmdb-main/internal/user"
	"github.com/userreksai/ecmdb-main/internal/workflow"
	"github.com/userreksai/ecmdb-main/ioc"
	grpc2 "github.com/userreksai/ecmdb-task/pkg/grpc"
	"github.com/userreksai/ecmdb-task/pkg/grpc/registry"
	"github.com/userreksai/ecmdb-task/pkg/grpc/registry/etcd"
	"go.etcd.io/etcd/client/v3"
	"google.golang.org/grpc"
	"time"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	mongo := ioc.InitMongoDB()
	client := ioc.InitRedisSearch()
	config := ioc.InitLdapConfig()
	db := ioc.InitMySQLDB()
	syncedEnforcer := ioc.InitCasbin(db)
	cmdable := ioc.InitRedis()
	provider := ioc.InitSession(cmdable)
	manager := servicetoken.NewManager()
	module, err := policy.InitModule(syncedEnforcer, provider, manager)
	if err != nil {
		return nil, err
	}
	departmentModule, err := department.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	cryptoRegistry := ioc.InitModuleCrypto()
	userModule, err := user.InitModule(mongo, client, config, module, departmentModule, provider, cryptoRegistry, manager)
	if err != nil {
		return nil, err
	}
	v := userModule.Svc
	roleModule, err := role.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	v2 := roleModule.Svc
	mq := ioc.InitMQ()
	menuModule, err := menu.InitModule(mq, mongo)
	if err != nil {
		return nil, err
	}
	v3 := menuModule.Svc
	relationModule, err := relation.InitModule(mongo, roleModule, module)
	if err != nil {
		return nil, err
	}
	attributeModule, err := attribute.InitModule(mongo, mq)
	if err != nil {
		return nil, err
	}
	operationlogModule, err := operationlog.InitModule(db)
	if err != nil {
		return nil, err
	}
	resourceModule, err := resource.InitModule(mongo, attributeModule, relationModule, mq, cryptoRegistry, roleModule, module, operationlogModule)
	if err != nil {
		return nil, err
	}
	modelModule, err := model.InitModule(mongo, relationModule, attributeModule, resourceModule, roleModule, module)
	if err != nil {
		return nil, err
	}
	permissionModule, err := permission.InitModule(mongo, mq, roleModule, menuModule, module, modelModule)
	if err != nil {
		return nil, err
	}
	v4 := permissionModule.Svc
	v5 := module.Svc
	dao := version.NewDao(mongo)
	service := version.NewService(dao)
	bootstrapModule, err := bootstrap.InitModule(modelModule, attributeModule, relationModule)
	if err != nil {
		return nil, err
	}
	v6 := bootstrapModule.Svc
	clientv3Client := ioc.InitEtcdClient()
	registry := InitRegistry(clientv3Client)
	clientConnInterface := InitEALERTGrpcClient(registry)
	templateServiceClient := InitTemplateServiceClient(clientConnInterface)
	engineModule, err := engine.InitModule(db)
	if err != nil {
		return nil, err
	}
	workflowModule, err := workflow.InitModule(mongo, engineModule)
	if err != nil {
		return nil, err
	}
	v7 := workflowModule.Svc
	app := &App{
		UserSvc:        v,
		RoleSvc:        v2,
		MenuSvc:        v3,
		PermissionSvc:  v4,
		policySvc:      v5,
		VerSvc:         service,
		BootstrapSvc:   v6,
		TemplateClient: templateServiceClient,
		WorkflowSvc:    v7,
		GormDB:         db,
		DB:             mongo,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(ioc.InitMongoDB, ioc.InitMySQLDB, ioc.InitRedis, ioc.InitRedisSearch, ioc.InitMQ, ioc.InitEtcdClient, ioc.InitLdapConfig, ioc.InitModuleCrypto)

// InitRegistry 初始化统一的服务注册中心
func InitRegistry(etcdClient *clientv3.Client) registry.Registry {
	r, err := etcd.NewRegistry(etcdClient)
	if err != nil {
		panic(err)
	}
	return r
}

// InitEALERTGrpcClient 初始化 EALERT gRPC 客户端
func InitEALERTGrpcClient(reg registry.Registry) grpc.ClientConnInterface {
	var cfg grpc2.ClientConfig
	if err := viper.UnmarshalKey("grpc.client.ealert", &cfg); err != nil {
		panic(err)
	}

	cc, err := grpc2.NewClientConn(
		reg, grpc2.WithServiceName(cfg.Name), grpc2.WithClientJWTAuth(cfg.AuthToken), grpc2.WithDialOption(grpc.WithConnectParams(grpc.ConnectParams{
			MinConnectTimeout: 3 * time.Second,
		}), grpc.WithDefaultCallOptions(grpc.WaitForReady(false))),
	)
	if err != nil {
		panic(err)
	}

	return cc
}

// InitTemplateServiceClient 初始化 template 服务客户端
func InitTemplateServiceClient(cc grpc.ClientConnInterface) templatev1.TemplateServiceClient {
	return templatev1.NewTemplateServiceClient(cc)
}
