// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/larksuite/oapi-sdk-go/v3"
	"github.com/userreksai/ecmdb-main/api/proto/gen/ealert/notification/v1"
	"github.com/userreksai/ecmdb-main/api/proto/gen/ealert/team"
	"github.com/userreksai/ecmdb-main/internal/department"
	"github.com/userreksai/ecmdb-main/internal/engine"
	"github.com/userreksai/ecmdb-main/internal/event"
	"github.com/userreksai/ecmdb-main/internal/event/producer"
	"github.com/userreksai/ecmdb-main/internal/event/service/assignees"
	"github.com/userreksai/ecmdb-main/internal/event/service/easyflow"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/automation"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/carbon_copy"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/chat"
	"github.com/userreksai/ecmdb-main/internal/event/service/strategy/start"
	user2 "github.com/userreksai/ecmdb-main/internal/event/service/strategy/user"
	"github.com/userreksai/ecmdb-main/internal/order"
	"github.com/userreksai/ecmdb-main/internal/pkg/notification/sender"
	"github.com/userreksai/ecmdb-main/internal/rota"
	"github.com/userreksai/ecmdb-main/internal/task"
	"github.com/userreksai/ecmdb-main/internal/template"
	"github.com/userreksai/ecmdb-main/internal/test/ioc"
	"github.com/userreksai/ecmdb-main/internal/user"
	"github.com/userreksai/ecmdb-main/internal/workflow"
)

// Injectors from wire.go:

func InitApp(sender2 sender.NotificationSender, teamSvc teamv1.TeamServiceClient, notificationSvc notificationv1.NotificationServiceClient, userModule *user.Module, orderModule *order.Module, taskModule *task.Module, templateModule *template.Module, engineModule *engine.Module, workflowModule *workflow.Module, departmentModule *department.Module, rotaModule *rota.Module) (*TestApp, error) {
	db := ioc.InitMySQLDB()
	v := engineModule.Svc
	mq := ioc.InitMQ()
	orderStatusModifyEventProducer, err := producer.NewOrderStatusModifyEventProducer(mq)
	if err != nil {
		return nil, err
	}
	v2 := taskModule.Svc
	v3 := orderModule.Svc
	v4 := workflowModule.Svc
	v5 := userModule.Svc
	v6 := templateModule.Svc
	appointResolver := assignees.NewAppointResolver(v5)
	founderResolver := assignees.NewFounderResolver(v5)
	v7 := departmentModule.Svc
	leaderResolver := assignees.NewLeaderResolver(v5, v7)
	mainLeaderResolver := assignees.NewMainLeaderResolver(v5, v7)
	v8 := rotaModule.Svc
	onCallResolver := assignees.NewOnCallResolver(v8, v5)
	templateResolver := assignees.NewTemplateResolver(v5)
	teamResolver := assignees.NewTeamResolver(teamSvc, v5)
	resolveEngine := event.InitResolveEngine(appointResolver, founderResolver, leaderResolver, mainLeaderResolver, onCallResolver, templateResolver, teamResolver)
	service := strategy.NewService(v5, v6, v2, v3, v, resolveEngine)
	notification := user2.NewNotification(service, v7, sender2, notificationSvc)
	automationNotification := automation.NewNotification(service, sender2)
	startNotification := start.NewNotification(service, sender2)
	client := _wireClientValue
	chatNotification := chat.NewNotification(service, sender2, client, teamSvc)
	carbon_copyNotification := carbon_copy.NewNotification(service, sender2)
	dispatcher := event.ProviderNewDispatcher(notification, automationNotification, startNotification, chatNotification, carbon_copyNotification, service)
	processEvent := event.InitWorkflowEngineOnce(db, v, orderStatusModifyEventProducer, v2, v3, v4, dispatcher)
	testApp := &TestApp{
		EventHandler:     processEvent,
		UserModule:       userModule,
		OrderModule:      orderModule,
		TaskModule:       taskModule,
		TemplateModule:   templateModule,
		EngineModule:     engineModule,
		WorkflowModule:   workflowModule,
		DepartmentModule: departmentModule,
		RotaModule:       rotaModule,
	}
	return testApp, nil
}

var (
	_wireClientValue = (*lark.Client)(nil)
)

// wire.go:

type TestApp struct {
	EventHandler     *easyflow.ProcessEvent
	UserModule       *user.Module
	OrderModule      *order.Module
	TaskModule       *task.Module
	TemplateModule   *template.Module
	EngineModule     *engine.Module
	WorkflowModule   *workflow.Module
	DepartmentModule *department.Module
	RotaModule       *rota.Module
}
