// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package department

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/department/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/department/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/department/internal/service"
	"github.com/userreksai/ecmdb-main/internal/department/internal/web"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	departmentDAO := dao.NewDepartmentDAO(db)
	departmentRepository := repository.NewDepartmentRepository(departmentDAO)
	serviceService := service.NewService(departmentRepository)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Hdl: handler,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewDepartmentRepository, dao.NewDepartmentDAO)
