// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/policy"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/role"
)

// Injectors from wire.go:

func InitRMHandler(roleModule *role.Module, policyModule *policy.Module) (*relation.RMHandler, error) {
	mongo := InitMongoDB()
	module, err := relation.InitModule(mongo, roleModule, policyModule)
	if err != nil {
		return nil, err
	}
	v := module.RMHdl
	return v, nil
}

func InitRRHandler(roleModule *role.Module, policyModule *policy.Module) (*relation.RRHandler, error) {
	mongo := InitMongoDB()
	module, err := relation.InitModule(mongo, roleModule, policyModule)
	if err != nil {
		return nil, err
	}
	v := module.RRHdl
	return v, nil
}

func InitRRSvc() relation.RRSvc {
	mongo := InitMongoDB()
	v := relation.InitRRService(mongo)
	return v
}

func InitRMSvc() relation.RMSvc {
	mongo := InitMongoDB()
	v := relation.InitRMService(mongo)
	return v
}
