// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/worker/internal/event"
	"github.com/userreksai/ecmdb-main/internal/worker/internal/job"
	"github.com/userreksai/ecmdb-main/internal/worker/internal/service"
	"github.com/userreksai/ecmdb-task/pkg/grpc/registry"
	"github.com/userreksai/ecmdb-task/pkg/grpc/registry/etcd"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, etcdClient *clientv3.Client) (*Module, error) {
	taskWorkerEventProducer, err := event.NewTaskRunnerEventProducer(q)
	if err != nil {
		return nil, err
	}
	v := service.NewService(q, taskWorkerEventProducer)
	registry, err := InitRegistry(etcdClient)
	if err != nil {
		return nil, err
	}
	serviceDiscoveryJob := initWatch(registry, v)
	module := &Module{
		Svc: v,
		Job: serviceDiscoveryJob,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewService, InitRegistry, wire.Bind(new(registry.Registry), new(*etcd.Registry)))

func initWatch(r registry.Registry, svc service.Service) *job.ServiceDiscoveryJob {
	task, err := job.NewServiceDiscoveryJob(r, svc)
	if err != nil {
		panic(err)
	}

	go task.Watch()
	return task
}

func InitRegistry(etcdClient *clientv3.Client) (*etcd.Registry, error) {
	return etcd.NewRegistryWithPrefix(etcdClient, "/etask/kafka")
}
