// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"context"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/attribute"
	"github.com/userreksai/ecmdb-main/internal/operationlog"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/relation"
	"github.com/userreksai/ecmdb-main/internal/resource/internal/event"
	"github.com/userreksai/ecmdb-main/internal/resource/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/resource/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/resource/internal/service"
	"github.com/userreksai/ecmdb-main/internal/resource/internal/web"
	"github.com/userreksai/ecmdb-main/internal/role"
	"github.com/userreksai/ecmdb-main/pkg/cryptox"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, attributeModule *attribute.Module, relationModule *relation.Module, q mq.MQ, crypto *cryptox.CryptoRegistry, roleModule *role.Module, policyModule *policy.Module, operationLogModule *operationlog.Module) (*Module, error) {
	resourceDAO := InitResourceDAO(db)
	resourceRepository := repository.NewResourceRepository(resourceDAO)
	v := NewService(resourceRepository)
	v2 := attributeModule.Svc
	cryptoxCrypto := InitCrypto(crypto)
	v3 := NewEncryptedService(v, v2, cryptoxCrypto)
	v4 := relationModule.RRSvc
	v5 := roleModule.Svc
	v6 := policyModule.Svc
	service := operationLogModule.Svc
	v7 := web.NewHandler(v3, v2, v4, v5, v6, service)
	fieldSecureAttrChangeConsumer := initConsumer(q, v3, cryptoxCrypto)
	module := &Module{
		Svc:          v,
		EncryptedSvc: v3,
		Hdl:          v7,
		c:            fieldSecureAttrChangeConsumer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, repository.NewResourceRepository)

var daoOnce = sync.Once{}

func InitCollectionOnce(db *mongox.Mongo) {
	daoOnce.Do(func() {
		err := dao.InitIndexes(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitResourceDAO(db *mongox.Mongo) dao.ResourceDAO {
	InitCollectionOnce(db)
	return dao.NewResourceDAO(db)
}

func NewService(repo repository.ResourceRepository) Service {
	return service.NewService(repo)
}

func NewEncryptedService(baseSvc service.Service, attrSvc attribute.Service, cryptox2 cryptox.Crypto,
) EncryptedSvc {
	return service.NewEncryptedResourceService(baseSvc, attrSvc, cryptox2)
}

func InitCrypto(reg *cryptox.CryptoRegistry) cryptox.Crypto {
	return reg.Resource
}

func initConsumer(q mq.MQ, svc service.EncryptedSvc, cryptox2 cryptox.Crypto) *event.FieldSecureAttrChangeConsumer {
	consumer, err := event.NewFieldSecureAttrChangeConsumer(q, svc, 20, cryptox2)
	if err != nil {
		panic(err)
	}

	consumer.Start(context.Background())
	return consumer
}
