// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tools

import (
	"github.com/userreksai/ecmdb-main/internal/tools/service"
	"github.com/userreksai/ecmdb-main/internal/tools/web"
	"github.com/userreksai/ecmdb-main/pkg/storage"
)

// Injectors from wire.go:

func InitModule(storage2 *storage.S3Storage) (*web.Handler, error) {
	serviceService := service.NewService(storage2)
	handler := web.NewHandler(serviceService)
	return handler, nil
}
