// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/RediSearch/redisearch-go/v2/redisearch"
	"github.com/ecodeclub/ginx/session"
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/department"
	"github.com/userreksai/ecmdb-main/internal/pkg/servicetoken"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/user/internal/grpc"
	"github.com/userreksai/ecmdb-main/internal/user/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/user/internal/repository/cache"
	"github.com/userreksai/ecmdb-main/internal/user/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/user/internal/service"
	"github.com/userreksai/ecmdb-main/internal/user/internal/web"
	"github.com/userreksai/ecmdb-main/internal/user/ldapx"
	"github.com/userreksai/ecmdb-main/pkg/cryptox"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, redisClient *redisearch.Client, ldapConfig ldapx.Config, policyModule *policy.Module, departmentModule *department.Module, sp session.Provider, crypto *cryptox.CryptoRegistry, tokenMgr *servicetoken.Manager) (*Module, error) {
	userDAO := dao.NewUserDao(db)
	userRepository := repository.NewResourceRepository(userDAO)
	v := policyModule.Svc
	cryptoxCrypto := InitCrypto(crypto)
	serviceService := service.NewService(userRepository, v, cryptoxCrypto)
	redisearchLdapUserCache := InitLdapUserCache(redisClient)
	ldapService := service.NewLdapService(ldapConfig, redisearchLdapUserCache)
	v2 := departmentModule.Svc
	handler := web.NewHandler(serviceService, ldapService, v2, sp, tokenMgr)
	v3 := grpc.NewUserServer(serviceService)
	module := &Module{
		Hdl:       handler,
		Svc:       serviceService,
		RpcServer: v3,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewLdapService, service.NewService, repository.NewResourceRepository, grpc.NewUserServer, dao.NewUserDao, web.NewHandler)

func InitLdapUserCache(conn *redisearch.Client) cache.RedisearchLdapUserCache {
	return cache.NewRedisearchLdapUserCache(conn)
}

func InitCrypto(reg *cryptox.CryptoRegistry) cryptox.Crypto {
	return reg.User
}
