// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package permission

import (
	"context"
	"github.com/Duke1616/ecmdb/internal/menu"
	"github.com/Duke1616/ecmdb/internal/model"
	"github.com/Duke1616/ecmdb/internal/permission/internal/event"
	"github.com/Duke1616/ecmdb/internal/permission/internal/service"
	"github.com/Duke1616/ecmdb/internal/permission/internal/web"
	"github.com/Duke1616/ecmdb/internal/policy"
	"github.com/Duke1616/ecmdb/internal/role"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/ecodeclub/mq-api"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, q mq.MQ, roleModule *role.Module, menuModule *menu.Module, policyModule *policy.Module, modelModule *model.Module) (*Module, error) {
	v := roleModule.Svc
	v2 := menuModule.Svc
	v3 := policyModule.Svc
	v4 := modelModule.Svc
	v5 := modelModule.MGSvc
	serviceService := service.NewService(v, v3, v2)
	v6 := web.NewHandler(v, v2, v3, v4, v5, serviceService)
	menuChangeEventConsumer := InitMenuChangeEventConsumer(q, serviceService)
	module := &Module{
		Hdl: v6,
		Svc: serviceService,
		c:   menuChangeEventConsumer,
	}
	return module, nil
}

// wire.go:

func InitMenuChangeEventConsumer(q mq.MQ, svc service.Service) *event.MenuChangeEventConsumer {
	c, err := event.NewMenuChangeEventConsumer(q, svc)
	if err != nil {
		return nil
	}

	c.Start(context.Background())
	return c
}
