// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/operationlog"
	"github.com/Duke1616/ecmdb/internal/policy"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/internal/role"
)

// Injectors from wire.go:

func InitHandler(attributeModule *attribute.Module, relationModule *relation.Module, roleModule *role.Module, policyModule *policy.Module) (*resource.Handler, error) {
	mongo := InitMongoDB()
	mq := InitMQ()
	cryptoRegistry := InitCryptoRegistry()
	module := InitOperationLogModule()
	resourceModule, err := resource.InitModule(mongo, attributeModule, relationModule, mq, cryptoRegistry, roleModule, policyModule, module)
	if err != nil {
		return nil, err
	}
	v := resourceModule.Hdl
	return v, nil
}

// wire.go:

func InitOperationLogModule() *operationlog.Module { return &operationlog.Module{} }
