// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/userreksai/ecmdb-main/internal/attribute"
	"github.com/userreksai/ecmdb-main/internal/model"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/relation"
	"github.com/userreksai/ecmdb-main/internal/resource"
	"github.com/userreksai/ecmdb-main/internal/role"
	"github.com/userreksai/ecmdb-main/internal/test/ioc"
)

// Injectors from wire.go:

func InitHandler(rmModule *relation.Module, attrModule *attribute.Module, resourceModule *resource.Module, roleModule *role.Module, policyModule *policy.Module) (*model.Handler, error) {
	mongo := ioc.InitMongoDB()
	module, err := model.InitModule(mongo, rmModule, attrModule, resourceModule, roleModule, policyModule)
	if err != nil {
		return nil, err
	}
	v := module.Hdl
	return v, nil
}
