// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package terminal

import (
	"github.com/userreksai/ecmdb-main/internal/attribute"
	"github.com/userreksai/ecmdb-main/internal/policy"
	"github.com/userreksai/ecmdb-main/internal/relation"
	"github.com/userreksai/ecmdb-main/internal/resource"
	"github.com/userreksai/ecmdb-main/internal/role"
	"github.com/userreksai/ecmdb-main/internal/terminal/internal/web"
)

// Injectors from wire.go:

func InitModule(relationModule *relation.Module, resourceModule *resource.Module, attributeModule *attribute.Module, roleModule *role.Module, policyModule *policy.Module) (*web.Handler, error) {
	v := relationModule.RRSvc
	v2 := resourceModule.EncryptedSvc
	v3 := attributeModule.Svc
	v4 := roleModule.Svc
	v5 := policyModule.Svc
	handler := web.NewHandler(v, v2, v3, v4, v5)
	return handler, nil
}
