// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package discovery

import (
	"github.com/google/wire"
	"github.com/userreksai/ecmdb-main/internal/discovery/internal/repository"
	"github.com/userreksai/ecmdb-main/internal/discovery/internal/repository/dao"
	"github.com/userreksai/ecmdb-main/internal/discovery/internal/service"
	"github.com/userreksai/ecmdb-main/internal/discovery/internal/web"
	"github.com/userreksai/ecmdb-main/pkg/mongox"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	discoveryDAO := dao.NewDiscoveryDAO(db)
	discoveryRepository := repository.NewDiscoveryRepository(discoveryDAO)
	v := service.NewService(discoveryRepository)
	v2 := web.NewHandler(v)
	module := &Module{
		Svc: v,
		Hdl: v2,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewDiscoveryRepository, dao.NewDiscoveryDAO)
